config/routes.rb
Pikachu::Application.routes.draw do
  
  resources :admins do
    collection do
      post :sort
    end
  end
  
  resources :users do
  	collection do
  		post :sort
  	end
  end

  resources :sessions
	get "signout" => "sessions#destroy", :as => "signout"
	get "signin" => "sessions#new", :as => "signin"
	get "register" => "users#new", :as => "register"
  
  root :to => "users#new"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can [:read, :update], User, :id => user.id
    cannot :index, User
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  ROLES = %w[simple super]
  
  attr_accessible :nickname, :firstname, :lastname, :email, :password, :password_confirmation, :role, :position
  
  attr_accessor :password
  
    before_save :encrypt_pass
    before_save { |admin| admin.email = email.downcase }

    validates :nickname, :presence => true, :uniqueness => true
    validates :password, :presence => true, :confirmation => true, length: { minimum: 7 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, :presence => true, format: { with: VALID_EMAIL_REGEX }, :uniqueness => { case_sensitive: false }
        
    def self.authenticate(email, password)
      admin = find_by_email(email)
      if admin && admin.password_hash == BCrypt::Engine.hash_secret(password, admin.password_salt)
        admin
      else
        nil
      end
    end
    
    def encrypt_pass
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end

    def self.search(search)
      if search
        where('nickname LIKE ?', "%#{search}%")
      else
        scoped
      end
    end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  
  def initialize(admin)
    can :manage, :all if admin && admin.role == "super"
    can [:read, :update], Admin, :id => admin.id
    can :index, [Admin, User]
    can :destroy, User
  end
end

app/models/guest_ability.rb
class GuestAbility
  include CanCan::Ability

  def initialize
  	can [:new, :create], User
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :nickname, :firstname, :lastname, :email, :password, :password_confirmation, :position
    
    attr_accessor :password
    before_save :encrypt_pass
    before_save { |user| user.email = email.downcase }

    validates :nickname, :presence => true, :uniqueness => true
    validates :password, :presence => true, :confirmation => true, length: { minimum: 7 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, :presence => true, format: { with: VALID_EMAIL_REGEX }, :uniqueness => { case_sensitive: false }
        
    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
    
    def encrypt_pass
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end



    def self.search(search)
      if search
        where('nickname LIKE ?', "%#{search}%")
      else
        scoped
      end
    end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_filter :load_admin, only: [:show, :edit, :update, :destroy]
	helper_method :sort_column, :sort_direction
	load_and_authorize_resource
	
 	def index
		@admins = Admin.search(params[:search]).order(sort_column + " " + sort_direction).page params[:page]
	end

	def new
		@admin = Admin.new
	end

	def create
	  @admin = Admin.new(params[:admin])
	  if @admin.save
	    redirect_to admins_path, :notice => "Admin was succesfully created!"
	  else
	    render "new"
	  end
	end

	def show
	end

	def edit
	end

	def update
     respond_to do |format|
	    if @admin.update_attributes(params[:admin])
	      format.html { redirect_to(@admin, :notice => "Admin was updated")}
	      format.js
	    else
	      format.html {render "edit"}
	      format.js
	    end
  	end
	end

	def destroy
		@admins = Admin.search(params[:search]).order(sort_column + " " + sort_direction).page params[:page]
		@admin.destroy
    respond_to do |format|
    	format.html { redirect_to(users_url, :notice => 'Admin destroyed!') }
    	format.js
		end
	end

	def sort
			params[:admin].each_with_index do |id, index|
	    	Admin.update_all({position: index+1}, {id: id})
	  	end
	  	render nothing: true
	end

	private

		def load_admin
			@admin = Admin.find(params[:id])
		end

   	def sort_column
	    Admin.column_names.include?(params[:sort]) ? params[:sort] : 'nickname'
	  end
	  
	  def sort_direction
	    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :current_admin
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
	
	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def current_admin
		@current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]		
	end

	def current_ability
		@current_ability ||= case 
												when current_user
													Ability.new(current_user)
												when current_admin
													AdminAbility.new(current_admin)
												else
                          GuestAbility.new
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  admin = Admin.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to user, :notice => "Logged in as #{user.nickname}!"
	  elsif admin
	    session[:admin_id] = admin.id
	    redirect_to users_path, :notice => "Logged in as #{admin.nickname}!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	 	session[:admin_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, except: [:index, :new, :create, :sort]
  helper_method :sort_column, :sort_direction
  load_and_authorize_resource except: :new

 	def index
		@users = User.search(params[:search]).order(sort_column + " " + sort_direction).page params[:page]
	end

	def new
		@user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	    redirect_to signin_path, :notice=> "Your account was successfully created!"
	  else
	    render "new"
	  end
	end

	def show
	end
	
	def edit
	end

	def update
    respond_to do |format|
	    if @user.update_attributes(params[:user])
	      format.html { redirect_to @user, :notice => "User was updated"}
	      format.js
	    else
	      format.html {render "edit"}
	      format.js
	    end
  	end
	end

	def destroy
		@users = User.search(params[:search]).order(sort_column + " " + sort_direction).page params[:page] 
		@user.destroy
		respond_to do |format|
    	format.html { redirect_to(users_url, :notice => 'User destroyed!') }
    	format.json
    	format.js
		end
	end

	def sort
		params[:user].each.with_index do |id, index|
    	User.update_all({position: index+1}, {id: id})
  	end
  	render nothing: true
	end

	private

		def set_user
			@user = User.find(params[:id])
		end

	  def sort_column
	    User.column_names.include?(params[:sort]) ? params[:sort] : 'nickname'
	  end
	  
	  def sort_direction
	    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
	  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_admins.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-hover table-condensed">
	<thead>
		<tr>
			<th><%= sortable 'nickname' %></th>
			<th><%= sortable 'firstname' %></th>
			<th><%= sortable 'lastname' %></th>
			<th><%= sortable "email" %></th>
			<th><%= sortable "role" %></th>
		</tr>
	</thead>
	<tbody>
	<% @admins.each do |admin|%>
		<%= content_tag_for :tr, admin do %>
			<tr>
			<td><%= admin.nickname %></td>
			<td><%= admin.firstname %></td>
			<td><%= admin.lastname %></td>
			<td><%= admin.email %></td>
			<td><%= admin.role %></td>
			<% if can? :edit, admin %>
				<td>
				<%= link_to "Edit", edit_admin_path(admin), remote: true, :class=>"btn btn-xs btn-primary" %>
				</td>
				<% end %>
			<% if can? :destroy, admin %>
				<td>
				<%= link_to "Destroy", admin, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, :class=>"btn btn-xs btn-danger", :id =>"destroy_admin" %>
				</td>
				<% end %>
			</tr>
		<% end %>
	<% end %>
	<tbody>
</table>
<%= paginate @admins %>

app/views/admins/_edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
    	<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  			<h3><%= "Editing #{@admin.nickname}" %></h3>
  		</div>
      <div class="modal-body">
      <%= render "form" %>
      </div>
    </div>
</div>

app/views/admins/_form.html.erb
<%= form_for @admin, remote: true do |f| %>
  <% if @admin.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @admin.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </p>
  <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <% if can? :manage, Admin%>
  <%= f.collection_select :role, Admin::ROLES, :to_s, :humanize %>
  <% end %>
  <p><%= f.submit "Save changes", :class=>"btn, btn-primary" %></p>
<% end %>

app/views/admins/destroy.js.erb
$("#admins").html("<%= escape_javascript(render("admins")) %>");

app/views/admins/edit.html.erb
<h2><%= "Editing #{@admin.nickname}" %></h2>

<div id="edit_admin"><%= render "form" %></div>

app/views/admins/edit.js.erb
$("#adminModal").html("<%= escape_javascript (render ("edit")) %>");
$("#adminModal").modal("show");

app/views/admins/index.html.erb
<h2>Admins</h2>

<%= form_tag admins_path, :method => 'get', :id => 'admins_search', :class=>"form-group" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', :class=>"btn btn-sm btn-primary" %>
  </p>
 <div id='admins' data-update-url='<%= sort_admins_path %>'><%= render 'admins' %></div>
<% end %>
<% if can? :create, Admin %>
<%= link_to "Create Admin", new_admin_path, :class=>"btn btn-sm btn-info" %>
<% end %>

<%= link_to "List of Users", users_path, :class=>"btn btn-sm btn-info" %>

<div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/admins/index.js.erb
$("#admins").html("<%= escape_javascript(render("admins")) %>");

app/views/admins/new.html.erb
<h2>Register</h2>

<%= form_for @admin do |f| %>
  <% if @admin.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @admin.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </p>
  <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.collection_select :role, Admin::ROLES, :to_s, :humanize %>
  <p><%= f.submit "Create admin", :class=>"btn, btn-primary" %></p>
<% end %>

app/views/admins/update.js.erb
$("#adminModal").html("<%= escape_javascript ("admins") %>");
$("#adminModal").modal("hide");

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse", role="navigation">
    <div class="container">
      <%= link_to "Pikachu", root_path, id: "logo" %>
      <nav>
        <ul class="nav nav-pills navbar-right">
           <li><%= link_to "Users", users_path %></li>
           <li><%= link_to "Admins", admins_path %></li>
           <% if current_admin %>
              <li class="navbar-text"><%= "Welcome, #{current_admin.nickname}"%></li>
              <li><%= link_to "Exit", signout_path %></li>
           <% elsif current_user %>
              <li class="navbar-text"><%= "Welcome, #{current_user.nickname}"%></li>
              <li><%= link_to "Exit", signout_path %></li>  
           <% else %>
              <li><%= link_to "Register", register_path %></li>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/application.html.erb
	<!DOCTYPE html>
<html>
<head>
  <title>Pikachu</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "/layouts/header" %>

<div>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-info" %>
<% end %>
</div>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/users/_edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
    	<div class="modal-header">
    		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  			<h3><%= "Editing #{@user.nickname}" %></h3>
  		</div>
      <div class="modal-body">
      <%= render "form" %>
      </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, remote: true do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </p>
  <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Save changes", :class => "btn btn-primary" %></p>
<% end %>

app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-hover table-condensed">
	<thead>
		<tr>
			<th><%= sortable "nickname" %></th>
			<th><%= sortable "firstname" %></th>
			<th><%= sortable "lastname" %></th>
			<th><%= sortable "email" %></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user|%>
			<%= content_tag_for :tr, user do %>
				<tr>
				<td><%= user.nickname %></td>
				<td><%= user.firstname %></td>
				<td><%= user.lastname %></td>
				<td><%= user.email %></td>
				<% if can? :edit, user %>
				<td>
				<%= link_to "Edit", edit_user_path(user), remote: true, :class=>"btn btn-xs btn-primary" %>
				</td>
				<% end %>
				<% if can? :destroy, user %>
				<td>
				<%= link_to "Destroy", user, remote: true, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-xs btn-danger", :id =>"destroy_user" %>
				</td>
				<% end %>	
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>
<%= paginate @users %><br>

app/views/users/destroy.js.erb
$("#users").html("<%= escape_javascript (render("users")) %>");

app/views/users/edit.html.erb
<h2><%= "Editing #{@user.nickname}" %></h2>

<div id="edit_user"><%= render "form" %></div>

app/views/users/edit.js.erb
$("#myModal").html("<%= escape_javascript (render ("edit")) %>");
$("#myModal").modal("show");

app/views/users/index.html.erb
<h2>Users</h2>

	<%= form_tag users_path, :method => 'get', :class=>"form-group", :id=>"users_search" do %>
    <%= text_field_tag :search, params[:search] %>
 		<button type="submit" class="btn btn-sm btn-primary">Search</button>
  <div id='users' data-update-url='<%= sort_users_path %>'><%= render 'users' %></div>
<% end %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/users/index.js.erb
$("#users").html("<%= escape_javascript (render("users")) %>");

app/views/users/new.html.erb
<h2>Register</h2>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </p>
  <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </p>
  <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <button class="btn btn-primary">Create User</button> 
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), remote: true %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/users/update.js.erb
$("#myModal").html("<%= escape_javascript ("users") %>");
$("#myModal").modal("hide");